table ml_churn_feature_importance

	column feature
		dataType: string
		summarizeBy: none
		sourceColumn: feature

	column auc_drop_when_shuffled
		dataType: double
		summarizeBy: none
		sourceColumn: auc_drop_when_shuffled

	partition ml_churn_feature_importance = m
		mode: import
		source =
				let
					Source = Csv.Document(File.Contents(DataPath & "\ml_churn_feature_importance.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
					Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
					Typed = Table.TransformColumnTypes(Promoted, {{"feature", type text}, {"auc_drop_when_shuffled", type number}}, "en-US")
				in
					Typed
